#!/usr/bin/env python

"""
TCP Preforked Server, Children Call 'accept'

Pool of child processes handle client requests.
"""

__author__ = 'hungnv <hungnv@opensource.com.vn>'

import optparse
from model import httputil, httpcompute

# stores pids of all preforked children
PIDS = []


def main():
	httpserver = httputil.HTTPServer()
	parser = optparse.OptionParser()
	parser.add_option(
        '-i', '--host', dest='host', default='0.0.0.0',
        help='Hostname or IP address. Default is 0.0.0.0'
        )
	parser.add_option(
        '-p', '--port', dest='port', type='int', default=2001,
        help='Port. Default is 2000')
	parser.add_option(
        '-n', '--child-num', dest='childnum', type='int', default=10,
        help='Number of children to prefork. Default is 10')

	options, args = parser.parse_args()

	httpserver.serve_forever(options.host, options.port, options.childnum)

if __name__ == '__main__':
    main()
